### ISSUE TITLE
How do I use require in this package?

### ISSUE THREAD

**Issue by whes1015** [Maaarcocr/pyes#1]
![IMG_20220421_093430](https://user-images.githubusercontent.com/44525760/164354087-14cc3b44-3cbe-45ad-a6ba-f9243347178a.jpg)

**Comment by whes1015** [comment]
Do I need a python environment to run this package?

**Comment by Maaarcocr** [comment]
The issue you're seeing is due to the fact that you're trying to require an es module. As suggested by the error, rather than using require("pyes"), you can you await  import("pyes")

That should make it work!
